name: Static Analysis Pipeline
on:
  push:
    branches-ignore:
      - dev

permissions:
  contents: write
  security-events: write  # Ensure the action can upload SARIF results    

jobs:
  tflint:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Cache TFLint plugin directory
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint and generate SARIF report
        run: |
          tflint -f sarif --chdir=infra/ --recursive > tflint.sarif
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tflint.sarif
          category: tflint

  checkov:
    name: 'Checkov Policies'
    runs-on: ubuntu-latest
    needs: tflint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Checkov PRISMA Policies
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          output_format: sarif
          output_file_path: prisma_policies.sarif
        continue-on-error: true

      - name: Upload Checkov SARIF Reports
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            prisma_policies.sarif
          category: checkov-analysis-1

      - name: Run Checkov CUSTOM Policies
        id: checkov_custom
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          external_checks_dirs: aws/custom_rules
          config_file: aws/CKV_CUSTOM_LIST.yaml
          output_format: sarif
          output_file_path: custom_policies.sarif
        continue-on-error: true

  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest  # Update to avoid using self-hosted
    needs: tflint

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          curl -fsSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install.sh | bash

      - name: run report
        run: |
          tfsec --format sarif --out tfsec.sarif .

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
          category: tfsec

  sonarqube:
    name: "SonarQube Analysis"
    runs-on: ubuntu-latest  # Update to avoid using self-hosted
    needs: tflint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-4.7.0.2747-linux/bin"

      - name: Install Terraform (if required)
        run: |
          sudo apt-get update && sudo apt-get install -y terraform

      - name: Run SonarQube scan
        run: |
          sonar-scanner \
          -Dsonar.organization=<your_organization> \
          -Dsonar.projectKey=<your_project_key> \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
